# Generated by Django 5.0.7 on 2024-08-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('NW', 'New'), ('OG', 'On Going'), ('EN', 'Ended')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team', models.ManyToManyField(to='employee.employee')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='employee.employee')),
            ],
        ),
    ]
